### PR TITLE
Update statics (for v1.9.5)

### PR DESCRIPTION
**Pull request by kblanks**
Merging this will trigger a new build which will push out a new update (with the latest changes) to clients on the edge channel.

@kaso17 After merging, run `git pull`, `git tag 'v1.9.5'` and `git push --tags` to trigger a release to the stable update channel.

### CODE REVIEW

**Comment by kblanks** [comment]
The next step after releasing this is to automate the generation of statics as part of the build process.

**Comment by kaso17** [comment]
Would have assumed that it'S regenerated automatically during the build process.
Can someone confirm that this fixed the missing definitions issues in the edge build now?

**Comment by kblanks** [comment]
I'll test it this evening.

**Comment by kblanks** [comment]
Appears to be working fine @kaso17 :)

NetHD tracker is available

**Comment by aroundmyroom** [comment]
great .. 
1.9.4-47-g5122940.
is running here now.

**Comment by kblanks** [comment]
bump for @kaso17 – release still needs to be tagged ✨

**Comment by kaso17** [comment]
done
https://travis-ci.org/cardigann/cardigann/builds/194050372
Not sure how long it will take until it reaches equinox

**Comment by kblanks** [comment]
Should only take a couple of minutes :)

**Comment by kblanks** [comment]
@kaso17 Looks like the tag got called `'v1.9.5'` including the quotes. That was probably my fault ._.

Care to re-try without the quotes?

**Comment by kaso17** [comment]
We're now at v1.9.8.

**Pull request merged**
