### PR TITLE
Add environment flag override for server mode

### PR DESCRIPTION
**Pull request by frebib**
Added the option to override common server flags with environment variables. This is particularly useful in container environments

Before:
```bash
cardigann server --bind=127.0.0.1 --debug
```

After:
```bash
CARDIGANN_DEBUG=true CARDIGANN_BIND=127.0.0.1 cardigann server
```

### CODE REVIEW

**Comment by DarthHTTP** [comment]
Double 👍 @frebib !

I reported https://github.com/cardigann/cardigann/issues/427 a bit earlier, also related to running it in a docker env + nginx reverse proxy. 
tldr; config.json pathprefix (https://github.com/cardigann/cardigann/blob/master/server/server.go#L33) for some reason doesn't get picked up. 
I'm trying to debug it right now but have no luck; 

What i'm trying to say is:
Would you please also test & consider the fact that prefix might come also from config ?

**Comment by frebib** [comment]
Yeah sure I'll try and investigate later and see what I can come up with

**Comment by frebib** [comment]
This is already implemented https://github.com/cardigann/cardigann/blob/1501db76e97a047c02c05b1c82f8b022cfd58a7a/config/config.go#L41

**Comment by DarthHTTP** [comment]
wasn't aware about it either.

**Comment by frebib** [comment]
@DarthHTTP The reason `pathprefix` in the config files is broken is because of a fundamental design issue in how configuration is handled and ordered. The fix is to rewrite all of the config management stuff so that it's actually intuitive (see #429).

Realistically that's never going to happen so I kinda bodge-fixed it in my fork https://github.com/spritsai/cardigann-server. It's pushed into a docker image https://hub.docker.com/r/spritsail/cardigann if you'd like to try that one

**Comment by DarthHTTP** [comment]
thanks for the deep dive into it, i started debugging it yesterday but didn't finish.
let's see how it goes with the PR;

i'm usually using linuxserver.io; https://github.com/linuxserver/docker-cardigann, will try spritsail's image right away.

**Comment by frebib** [comment]
If there's anything with the spritsail image that isn't working for you or
there's something you'd like added let me know. The documentation is sparse
because I've not had time

**Comment by frebib** [comment]
Try `CARDIGANN_PREFIX`. I can't remember why but it's working for me

**Comment by DarthHTTP** [comment]
thanks, yes, works;

`-e CARDIGANN_PREFIX=/cardigann/`

**Comment by frebib** [comment]
I'd consider this still broken because if you consider the scenario where
only access to the subdirectory is given then this nginx redirect cannot be
put in place and should not be relied upon.

**Pull request closed without merging**
