### PR TITLE
Update bitmetv definition

### LINKED ISSUE #184: test 1.9.3: fail Bitmetv due to match selector
→ Indexer bitmetv FAILED with Failed to match selector "span.smallfont > font[color=\"#000000\"]"
ERRO[0037] Test failed                                   error=Failed to match selector "span.smallfont > font[color=\"#000000\"]"

DEBU[0031] Checking page test block                      path=https://www.bitmetv.org/messages.php selector= site=bitmetv
DEBU[0031] Resolving url                                 base=http://www.bitmetv.org/login.php?returnto=%2Fmessages.php site=bitmetv u=https://www.bitmetv.org/messages.php
DEBU[0031] Opening page                                  site=bitmetv url=https://www.bitmetv.org/messages.php
DEBU[0032] Finished request                              code=200 page=https://www.bitmetv.org/messages.php site=bitmetv
DEBU[0032] Successfully logged in                        site=bitmetv
DEBU[0032] Resolving url                                 base=https://www.bitmetv.org/messages.php site=bitmetv u=https://www.bitmetv.org/browse.php
DEBU[0032] Opening page                                  site=bitmetv url=https://www.bitmetv.org/browse.php
DEBU[0037] Finished request                              code=200 page=https://www.bitmetv.org/browse.php site=bitmetv
DEBU[0037] Ratio returned
FAILURE ✗ in 7.780718391s
→ Indexer bitmetv FAILED with Failed to match selector "span.smallfont > font[color=\"#000000\"]"
ERRO[0037] Test failed                                   error=Failed to match selector "span.smallfont > font[color=\"#000000\"]"

### PR DESCRIPTION
**Pull request by kaso17**
Fix #184

### CODE REVIEW

**Comment by aroundmyroom** [comment]
I saw the difference,  tried to have it +1 but i failed ;-)

**Comment by kaso17** [comment]
You either can wait for @lxt2 to release a new build with the fixes or download the updated definition and place it in the corresponding directory.
As it just affects the ratio you shouldn't have any problem during normal search, etc.

**Comment by aroundmyroom** [comment]
I read that the binary has the definitions included. But does the binary keep track of changes placed outside like in /user/.config/cardigann/definitions ?

**Comment by kaso17** [comment]
Yes, placing the definitions in the users definitions directory will override the internal one.

**Pull request merged**
