### PR TITLE
Add PublishDate to Potato Feed

### PR DESCRIPTION
**Pull request by onedr0p**
Thanks for submitting a pull request! If you aren't submitting a new indexer definition, you can delete all this text and write a summary of your change.

For a new indexer, please follow this checklist:

- [ ] Run `cardigann test definitions/trackername.yml` and include the output here:

```
Definition file for alpharatio parsed OK ✓
Testing indexer alpharatio
Indexer alpharatio passed ✓
``` 

- [ ] Make sure to add the indexer to the list in the README

If you run into issues with testing, remember you can run a debug test with `cardigann test --debug --cachepages definitions/trackername.yml`.

### CODE REVIEW

**Comment by onedr0p** [comment]
In case you're wondering it was added to the CouchPotato wiki

https://github.com/CouchPotato/CouchPotatoServer/wiki/Couchpotato-torrent-provider

**Comment by kaso17** [comment]
Can you update the code to make it UTC ISO 8601 format?

**Comment by kaso17** [comment]
And does this work if an indexer doesn't set the date field?

**Comment by onedr0p** [comment]
@kaso17 I do not know GoLang that well, perhaps you can add the date to reflect that format? I made this PR with the hopes you would help out a bit.

Also, if the indexer doesn't support date, I don't expect it to break anything, it would just not be present in the API call (like how IMDBID doesn't exist for some).

**Comment by kaso17** [comment]
We're probably at a similar skill level regarding GoLang ;)
You probably have to change the datatype to string and call Time.UTC().Format("...") during the assignment.
`item.PublishDate.UTC().Format(time.RFC3339)` might work.
If that format constant doesn't result in the expected layout you probably have to build your own format string.
In that case I recommend http://fuckinggodateformat.com/

**Comment by onedr0p** [comment]
@kaso17 feel free to modify my PR this is over my head.

**Comment by onedr0p** [comment]
Also see here #327 these are essential for Radarr working well with cardigann, please if you can prioritize them. Thanks 👍

**Comment by kaso17** [comment]
@lxt2 disappeared and I've no plans to become the new main developer of cardigann leaving this project more or less dead for now.
@kblanks agreed on helping with it as good as he can, maybe he can help with this one too.

**Comment by onedr0p** [comment]
Maybe one of you guys should fork this repo, and leave a message in the readme here about this being dead? Or should we just advise people to use jackett instead?

**Comment by kaso17** [comment]
@kblanks is already preparing the fork.

The main reasons why cardigann was born were frequent Jackett crashes in certain environments (Many of them have been fixed recently). A secondary reason was the mono requirement leading to an overall higher resource footprint. The mono argument isn't very strong in combination with Radarr.

Jackett supports all trackers (and many more) supported by cardigann at the same or better level. So unless you're planning to run it on a super memory constraint embedded system Jackett is the better option at this time, especially with the unknown future of cardigann.

**Comment by Dnkhatri** [comment]
I came to cardigann for 2 major reasons frequent crashes in old jackett
and the newer version of jackett not supporting public  trackers. With
cardigann definitions now supported in new jackett cardigann is becoming
obsolete unless some takes up the development.

**Pull request closed without merging**
