### PR TITLE
fix eztv definition

### PR DESCRIPTION
**Pull request by sstamoulis**
Fixed eztv definition, which downloaded episode page instead of torrent file.

### CODE REVIEW

**Comment by lxt2** [comment]
Interesting, I haven't seen any other complaints about this.

**Comment by torrentman** [comment]
It happens to me every time, and one other guy reported it too (under issues)

**Comment by peabnuts123** [comment]
Getting same issue, please merge!

**Comment by peabnuts123** [comment]
When can I expect to see this in a release? Having trouble building this for myself.

**Comment by peabnuts123** [comment]
Is this in the Edge channel ... ?

**Comment by kblanks** [comment]
@peabnuts123 The main dev is currently away, and the release system is broken (for edge builds too). For now you'll have to manually update the definition file on your client until it's sorted.

**Comment by peabnuts123** [comment]
How might I achieve this? The releases seem to just be a single .exe haha, and I had difficulty getting the project to build (because I am not a GO developer...)

**Pull request merged**
