### PR TITLE
Add metal-tracker.com Indexer

### LINKED ISSUE #375: Indexer Request: en.Metal-Tracker.com
### Indexer language: English trough en.metal-tracker.com and russian trough www.metal-tracker.com

I tried making the YML but am learning as I go and could not get Cardigann to work with it. I always get the error "Indexer not Found"

This is what I got so far:

`  site: metal
  type: semi-private
  name: metaltracker
  language: ru-ru
  encoding: UTF-8

  links:
    - http://www.metal-tracker.com/
    - http://en.metal-tracker.com/

  caps:
    categories:
      16: Audio

    modes:
      search: [q]

  login:
    path: /user/login.html
    form: "form"

    inputs:
      UserLogin[username]: "{{ .Config.username }}"
      UserLogin[password]: "{{ .Config.password }}"

    error:
      - path: /user/login.html

        message:
          selector: "#login_error"

    test:
      path: /user/login.html

  ratio:
    text: "0"

  search:

    path: /torrents/search.html

    inputs:

       $raw: 'search={{replace .Keywords " " "*" -1}}'

    rows:

      selector: "table.t_table tr:nth-child(n + 3)"

    fields:

      download:

        selector: "td:nth-child(1) a[href*='d.php']"

        attribute: href

      category:

        text: "16"

      title:

        selector: "td:nth-child(2)"

      details:

        selector: "td:nth-child(2) a"

        attribute: href

      size:

        selector: "td:nth-child(3)"

      date:

        selector: "td:nth-child(4)"

      seeders:

        selector: "td:nth-child(5)"

      #leechers:

        #selector: "td:nth-child(6)"

      downloadvolumefactor:

        text: "0"

      uploadvolumefactor:

        text: "1"
`

### PR DESCRIPTION
**Pull request by mirwan**
Inspired by Jackett and comments in the related issue. 
Date has been set to "today" which appears as "in an hour".
Not yet tested with headphones...

- [ ] Run `cardigann test definitions/metaltracker.yml` 

```
→ Testing 1 definition(s) (1.9.10-6-g70a254b/linux/amd64)
→ Testing indexer metaltracker at http://en.metal-tracker.com/
  Testing required config is available SUCCESS ✓ in 2.164954ms
  Testing login with valid credentials SUCCESS ✓ in 1.767531041s
  Testing search mode "search" SUCCESS ✓ in 2.650540518s
  Testing search mode "music-search" SUCCESS ✓ in 2.430225372s
  Testing empty results are handled SUCCESS ✓ in 865.36451ms
  Testing ratio SUCCESS ✓ in 174.579µs
→ Indexer metaltracker is OK
``` 

- [ ] Added to the README

It may close #375

### CODE REVIEW

**Comment by joelstitch** [comment]
Not working with headphones for me. On cardigann searches come out great but Headphones show no results when I do a search.

**Comment by mirwan** [comment]
Hi,
Actually you're right but I don't think this is due to the definition. I guess the search on metal-tracker.com is buggy: On the site, search "Morbid Angel Kingdoms Disdained" and there is not torrent found, but search "Morbid Angel" and the first 2 results are torrents of Kingdoms Disdained album...

**Comment by mirwan** [comment]
Apparently, the issue about search with both album and artist has been brought to the attention of the maintainer of metal-tracker.com and it seems that he is working on a fix.
Btw, just rebased to fix the conflict on README.

**Comment by joelstitch** [comment]
I love you mirwan

**Comment by mirwan** [comment]
Seems like the maintainer of metal-tracker.com delivered us a new year gift as the search with both artist and album has been implemented.
I confirm it works like a charm with headphones.

**Comment by joelstitch** [comment]
I can confirm is working for me also! Thanks so much for all the help. I'm going to try to get punktorrents.com working soon hopefully also.

**Comment by mirwan** [comment]
Just rebased. 
@lxt2 What do you think?

**Comment by mirwan** [comment]
Ping @kylegrantlucas @kaso17

**Comment by kaso17** [comment]
merged it but I believe this project is dead...

**Pull request merged**
