### PR TITLE
Update alpharatio definition

### LINKED ISSUE #62: AlphaRatio not working
When testing AlphaRatio I get the response:   

> An error occurred
> Failed to match selector "td:nth-child(5) .time"

### PR DESCRIPTION
**Pull request by tadfisher**
Fixes #62

### CODE REVIEW

**Comment by lxt2** [comment]
Ugh, unfortunately I'm seeing errors when testing this locally.

**Comment by lxt2** [comment]
Are you able to run `cardigann test --debug definitions/alpharatio.yml` and post the html output you get for a row? I get:

```
DEBU[0013] Processing row                                html=<tr class="torrent">
  <td>
  </td>
  <td class="center cats_col">
    <a href="./torrents.php?groupname=&amp;action=basic&amp;freetorrent=&amp;filter_cat[2]=1">
      <div title="" class="cats_tvhd tags_">
      </div>
    </a>
  </td>
  <td class="big_info">
    <div class="group_info clear">
      <span>
        					[ 
        <a href="torrents.php?action=download&amp;id=439855&amp;authkey=r̶e̶d̶a̶c̶t̶e̶d̶&amp;torrent_pass=r̶e̶d̶a̶c̶t̶e̶d̶&amp;id=439855&amp;authkey=r̶e̶d̶a̶c̶t̶e̶d̶&amp;torrent_pass=r̶e̶d̶a̶c̶t̶e̶d̶&amp;usetoken=r̶e̶d̶a̶c̶t̶e̶d̶&#39;Are you sure you want to use a freeleech token here?&#39;);">
          FL
        </a>
        					| 
        <a href="reportsv2.php?action=report&amp;id=439855" title="Report">
          RP
        </a>
         ]
        				
      </span>
      <a href="torrents.php?id=439884&amp;torrentid=439855#torrent439855" title="View Auto Torrent" dir="ltr">
        Those.Who.Cant.S02E01.PROPER.720p.HDTV.x264-W4F
      </a>
       / 
      <font color="#33A1FF">
        <strong class="torrent_label tl_notice" title="Scene">
          Scene
        </strong>
      </font>
      <div class="torrent_info">
      </div>
      <div class="tags">
      </div>
    </div>
  </td>
  <td>
    17
  </td>
  <td class="nobr">
    <span class="time" title="Oct 10 2016, 06:08">
      1 min ago
    </span>
  </td>
  <td class="nobr">
    710.17 MB
  </td>
  <td>
    0
  </td>
  <td>
    1
  </td>
  <td>
    1
  </td>
</tr> site=alpharatio
```

**Comment by tadfisher** [comment]
@lxt2 Mine is missing the `<td>17</td>` column.

**Comment by tadfisher** [comment]
Sorry, that was incorrect. Full output:

```
DEBU[0003] Found 50 rows                                 limit=3 offset=0 rows=50 selector=table#torrent_table tr.torrent site=alpharatio
DEBU[0003] Processing row                                html=<tr class="torrent">
  <td class="center cats_col">
    <a href="./torrents.php?groupname=&amp;action=basic&amp;freetorrent=&amp;filter_cat[2]=1">
      <div title="" class="cats_tvhd tags_">
      </div>
    </a>
  </td>
  <td class="big_info">
    <div class="group_info clear">
      <span>
                                                [ 
        <a href="torrents.php?action=download&amp;id=440051&amp;authkey=r̶e̶d̶a̶c̶t̶e̶d̶&amp;torrent_pass=r̶e̶d̶a̶c̶t̶e̶d̶&amp;id=440051&amp;authkey=r̶e̶d̶a̶c̶t̶e̶d̶&amp;torrent_pass=r̶e̶d̶a̶c̶t̶e̶d̶&amp;usetoken=r̶e̶d̶a̶c̶t̶e̶d̶&#39;Are you sure you want to use a freeleech token here?&#39;);">
          FL
        </a>
                                                | 
        <a href="reportsv2.php?action=report&amp;id=440051" title="Report">
          RP
        </a>
         ]
        
      </span>
      <a href="torrents.php?id=440080&amp;torrentid=440051#torrent440051" title="View Auto Torrent" dir="ltr">
        The.Block.AU.S12E29.720p.HDTV.x264-ORENJI
      </a>
       / 
      <font color="#33A1FF">
        <strong class="torrent_label tl_notice" title="Scene">
          Scene
        </strong>
      </font>
      <div class="torrent_info">
      </div>
      <div class="tags">
      </div>
    </div>
  </td>
  <td>
    21
  </td>
  <td class="nobr">
    <span class="time" title="Oct 10 2016, 21:07">
      Just now
    </span>
  </td>
  <td class="nobr">
    883.70 MB
  </td>
  <td>
    0
  </td>
  <td class="r00">
    0
  </td>
  <td>
    0
  </td>
</tr> site=alpharatio
DEBU[0003] Processing field "category"                   block=Selector(td.cats_col a) row=1 site=alpharatio
DEBU[0003] Extracting text from selection                html=<a href="./torrents.php?groupname=&amp;action=basic&amp;freetorrent=&amp;filter_cat[2]=1">
  <div title="" class="cats_tvhd tags_">
  </div>
</a> site=alpharatio
DEBU[0003] Applying filter regexp                        args=filter_cat\[\d+\]=(\d+) before=./torrents.php?groupname=&action=basic&freetorrent=&filter_cat[2]=1 site=alpharatio
DEBU[0003] Regex matched                                 matches=[filter_cat[2]=1 1] site=alpharatio
DEBU[0003] Finished processing field "category"          output=1 row=1 site=alpharatio
DEBU[0003] Processing field "title"                      block=Selector(td.big_info .group_info > a:nth-child(2)) row=1 site=alpharatio
DEBU[0003] Extracting text from selection                html=<a href="torrents.php?id=440080&amp;torrentid=440051#torrent440051" title="View Auto Torrent" dir="ltr">
  The.Block.AU.S12E29.720p.HDTV.x264-ORENJI
</a> site=alpharatio
DEBU[0003] Finished processing field "title"             output=The.Block.AU.S12E29.720p.HDTV.x264-ORENJI row=1 site=alpharatio
DEBU[0003] Processing field "details"                    block=Selector(td.big_info .group_info > a:nth-child(2)) row=1 site=alpharatio
DEBU[0003] Extracting text from selection                html=<a href="torrents.php?id=440080&amp;torrentid=440051#torrent440051" title="View Auto Torrent" dir="ltr">
  The.Block.AU.S12E29.720p.HDTV.x264-ORENJI
</a> site=alpharatio
DEBU[0003] Finished processing field "details"           output=torrents.php?id=440080&torrentid=440051#torrent440051 row=1 site=alpharatio
DEBU[0003] Processing field "download"                   block=Selector(td.big_info span a:nth-child(1)) row=1 site=alpharatio
DEBU[0003] Extracting text from selection                html=<a href="torrents.php?action=download&amp;id=440051&amp;authkey=r̶e̶d̶a̶c̶t̶e̶d̶&amp;torrent_pass=r̶e̶d̶a̶c̶t̶e̶d̶ site=alpharatio
DEBU[0003] Finished processing field "download"          output=torrents.php?action=download&id=440051&authkey=r̶e̶d̶a̶c̶t̶e̶d̶&torrent_pass=r̶e̶d̶a̶c̶t̶e̶d̶ row=1 site=alpharatio
DEBU[0003] Processing field "size"                       block=Selector(td:nth-child(6)) row=1 site=alpharatio
DEBU[0003] Extracting text from selection                html=<td>
  0
</td> site=alpharatio
DEBU[0003] Finished processing field "size"              output=0 row=1 site=alpharatio
DEBU[0003] Processing field "date"                       block=Selector(td:nth-child(5) .time) row=1 site=alpharatio
```

**Pull request merged**
