### PR TITLE
Add Xthor French Private Tracker

### PR DESCRIPTION
**Pull request by JigSawFr**
New Definition for French Private Tracker

- [x] Run `cardigann test definitions/xthor.yml` and include the output here:

```
PS D:\Projets\cardigann-dev> .\cardigann.exe test definitions/xthor.yml
→ Testing 1 definition(s) (1.9.4/windows/amd64)
→ Testing indexer xthor at https://xthor.bz/
  Testing required config is available SUCCESS ✓ in 0s
  Testing login with valid credentials SUCCESS ✓ in 392.2084ms
  Testing search mode "search" SUCCESS ✓ in 884.5808ms
  Testing search mode "tv-search" SUCCESS ✓ in 700.9818ms
  Testing empty results are handled SUCCESS ✓ in 668.3647ms
  Testing ratio SUCCESS ✓ in 0s
→ Indexer xthor is OK
``` 

- [x] Make sure to add the indexer to the list in the README

### CODE REVIEW

**Comment by JigSawFr** [comment]
Login method used is cookie.
As it's impossible now to bypass SimpleCaptcha https://github.com/cardigann/cardigann/issues/228

**Comment by kaso17** [comment]
For me it's using simple captcha without images (just the click X submit button)
If you use login method=post and post directly to takelogin.php including submitme: "X" it should work without #228.

**Comment by raspdealer** [comment]
Hi @kaso17 and @JigSawFr ,

For Xthor in Jackett, a simple PassKey is enough can't we use the same method?

**Comment by kaso17** [comment]
I've no access to the tracker, I can't help with it.

**Comment by JigSawFr** [comment]
@raspdealer modifications must be made on Jackett side. As a simple key is enough to access Xthor API, can you describe your problem ?

**Comment by raspdealer** [comment]
I was just wondering why talking about captcha as Jacektt is only asking for passkey to work :)
But if it's work like this it's great !!!

**Pull request merged**
