### PR TITLE
Update definitions and statics (v1.9.9)

### PR DESCRIPTION
**Pull request by kblanks**
I made a mistake with the previous PR – it turns out the statics are just for the web app and not the definitions. The only reason the previous builds worked for me are because I was running them from the repository root, which included the definitions folder.

To compile the definitions into the `indexer/definitions.go` file you have to run `make clean-statics` first.

@kaso17 Feel free to test and tag this as `v1.9.9`.

### CODE REVIEW

**Comment by kblanks** [comment]
I can confirm that it actually works now after moving it to an isolated location.

NetHD appears

**Comment by kaso17** [comment]
merged, v1.9.9 is release, v1.9.8 deleted.

Just wondering:
What happens if we delete the static.go/definitions.go files completely, are they automatically regenerated during the build?
That way we might be able to fix the equinox build.

**Comment by wasgehthierab** [comment]
thx!

**Comment by kblanks** [comment]
@kaso17 It looks to me like the equinox configuration is encrypted for Travis, so the only way to find out if that works is to try it.

**Comment by kaso17** [comment]
Deleting them breaks the travis build:
https://travis-ci.org/cardigann/cardigann/builds/194874828

**Pull request merged**
