### PR TITLE
Change Xthor Tracker login method to POST

### PR DESCRIPTION
**Pull request by JigSawFr**
Thanks to @Kaso17

### CODE REVIEW

**Comment by maxcore** [comment]
@JigSawFr how install with synology .. you can point me some info or link ?

**Comment by JigSawFr** [comment]
@maxcore you can use Docker on Synology if you are eligible https://www.cachem.fr/synology-dsm-docker/
As i don't have Synology NAS, i can't help you more... sorry.

**Comment by maxcore** [comment]
docker was perfect for me ! thx for the link !! 


you know when you push the build for jackett ?

**Comment by JigSawFr** [comment]
@maxcore i use on my side linuxserver's image, take a look at https://github.com/linuxserver/docker-cardigann
As config folder is exposed outside the container, you can add your own definitions
`config/definitions`
Just put this file https://raw.githubusercontent.com/JigSawFr/cardigann/definitions/xthor/definitions/xthor.yml in your definitions folder ;)

**Comment by maxcore** [comment]
nice work perfect :)

**Pull request merged**
